name: Dog API Automation Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Executar Testes de API
        run: mvn test -Drunner.class=Api

      - name: Upload do Relatório de Testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-reports
          path: target/cucumber-reports/